version: "3"

services:
  database:
    image: postgres:latest
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=agregador"
    ports:
      - 5432:5432
    volumes:
      - /pg-data:/var/lib/postgres/data
